<template>
    <b-container fluid class="about mb-5 p-0">
      <div v-for="answer, question, index in faq" :key="index" class="faq-item" role="tablist">
        <b-card class="faq-card" no-body>
          <b-card-header class="faq-question p-0" header-tag="header" role="tab">
            <b-button variant="light" block v-b-toggle="'accordion-' + index">
              {{ question }}
              <b-icon-plus class="icon-plus"></b-icon-plus>
            </b-button>
          </b-card-header>
          <b-collapse class="faq-answer " :id="'accordion-' + index" accordion="faq-accordion" role="tabpanel">
            <b-card-body>
              <b-card-text>{{ answer }}</b-card-text>
            </b-card-body>
          </b-collapse>
        </b-card>
      </div>
    </b-container>
</template>

<script>
    // @ is an alias to /src
    //import Vue from 'vue'
    import Component from 'vue-class-component'
    import {Vue} from "vue-property-decorator";
    import { BIconPlus } from 'bootstrap-vue'


    @Component({
        components: {
          BIconPlus
        }
    })

    export default class About extends Vue {

      faq = {
          "What is LICX?" : "LICX is an IRC2 token that represents staked ICX in the pool. It is the foundation for future DeFi solutions built by block42 on the ICON network.",
          "Advantages of staking with LICX?" : "Staking ICX into LICX pool allows you to still transfer tokens from one wallet to another.",
          "How do I use the LICX Smart contract?": "Easiest use of LICX is through our web application licx.finance",
          "When and how will I receive rewards?": "Rewards are generated every 43,120 blocks which is a bit over 24 hours. Staking rewards are distributed to users directly in form of LICX and the ICX generated by the pool is automatically restaked.",
          "Is there a minimum amount of LICX to receive rewards?": "Yes. To prevent attacks the wallets with amounts smaller than 1/10/100 are not eligible for rewards.",
          "How is voting handled?": "MVP will vote directly for block42 P-rep, the first upgrade on the version will allow users to distribute their votes in form of % to any P-rep",
          "Does anyone have access to the pooled funds?": "No. The funds can only be retrieved by sending LICX into the smart contract and everything is processed on the decentralized ICON network.",
          "What is the purpose of LICX?": "LICX is the base foundation for DeFi solutions we are building. It will allow earning staking rewards as well as interaction with other projects and Dapps.",
          "Is the exchange ratio from LICX:ICX or vice versa always 1:1?": "Yes. Exchanging LICX<->ICX through our web application (via smart contract) always has 1:1 ratio.",
          "Plans about future implementations": "Faster unstaking swaps, more DeFi solutions that are connected to LICX and integration of LICX into Dapps.",
          "Can I contribute (ideas)?": "Of course. If you have any great ideas feel free to tell us in our telegram group https://t.me/block42_icon",
          "Is this a token sale?": "No. There is no token sale, you will always be able to exchange ICX into LICX and vice versa",
          "Does LICX automatically restake my rewards?": "Yes. Because rewards are distributed in the form of LICX, ICX that was generated as rewards for staking in the pool gets automatically restaked.",
          "What about transaction fees?": "When entering and exiting the pool users pay the transaction fees. For reward distribution the transaction fees are taken from the rewards. The amounts of burned ICX for this purpose are minimal. Note: Transaction fees can only be paid in ICX."
      }
    }
</script>

<style lang="scss">
.about{
  position: relative;
  box-shadow: 0px 7px 28px lightgray;
  width: 65%;
  .faq-item{
    .faq-card{
      border: none;
      border-bottom: 2px solid rgba(182, 202, 204, 1);
      border-radius: 0;
      text-align: left;
      .faq-question{
        button{
          text-align: left;
          color: black;
          //background: white;

          border: none;
          border-radius: 0;

          font-size: 1.35em;
          font-weight: 700;

          padding: 0.6em 1em;
          svg{
            float: right;
          }
        }
      }
      .faq-answer{
        color: black;
        font-size: 1.1em;
      }
    }
  }
}
</style>
